### ISSUE TITLE
makefile for latexml compilation 

### ISSUE THREAD

**Issue by angerhang** [angerhang/mockDoc#10]
Create a makefile that complies doc.tex in latexml.

**Comment by kohlhase** [comment]
I am reopening: this is a Makefile allright, but not a very useful one. 

you want it to do more: 
- do the rnc2rng translation, so that it retransforms automatically whenever you change `mockdock.rnc` 
- the pdf transformation, 
- probably more in the future. 

Use it as a tool.

**Comment by angerhang** [comment]
I am not entirely sure about the conversion method used in our makefile. That's why I added trang into our repository too.

**Comment by kohlhase** [comment]
Just to give you a hint at future extensions, I have reworked the Makefile, please try to unerstannd what is happening there, so that you are equipped for further experiments.
