### ISSUE TITLE
make an XSLT from mockDoc to HTML5

### ISSUE THREAD

**Issue by kohlhase** [angerhang/mockDoc#13]
This is an extension (also of #5) to cover basic xslt integration.

**Comment by angerhang** [comment]
How deep we need to dig into for mockDoc? 
Is there any aspect that I am missing for xslt?

**Comment by kohlhase** [comment]
The complexity of the style sheet is OK, I just want something very simple so that we can talk about this in the howto. 

But interestingly, just like in the grammar you seem to have a preference for deep nesting. 
Usually XSLT style sheets are done differently: one template per element and then use `<xsl:apply-templates/>` to recurse. This is much more flexible and easier to maintain. 

I made a start on this, please complete.

**Comment by kohlhase** [comment]
When this is fixed,  we only need to write about it in #5.

**Comment by angerhang** [comment]
It should be fixed now.
