### ISSUE TITLE
make a mockDoc profile

### ISSUE THREAD

**Issue by kohlhase** [angerhang/mockDoc#14]
We want to cover many aspects of binding development in #5, so a profile would be nice.

**Comment by angerhang** [comment]
As I can't fine much info about the profile in LaTeXML manual, I wonder if we talking about a Perl profile here?

**Comment by kohlhase** [comment]
No, I am talking about `LaTeXML/lib/LaTeXML/resources/Profiles/*.opt`. They allow us to abbreviate a bunch of optional arguments into `--profile foo`, if the options are put into `foo.opt`. If profiles are  are not documented, then we in the manual, you should open an issue about this in LaTeXML. @dginev
can give advice on this.

**Comment by dginev** [comment]
Profiles are likely to still remain undocumented, as they are a beta feature and we haven't finalized their full specification as a feature. 

For example, here is the math profile (takes a TeX math snippet and gives back an HTML5 math expression):
https://github.com/brucemiller/LaTeXML/blob/master/lib/LaTeXML/resources/Profiles/math.opt

**Comment by angerhang** [comment]
As profiles are not documented yet, we decided not to include it in the current mockDoc::howTo.
